In [2]:
import numpy as np

In [3]:
x=[1,2,3,4]

In [4]:
nx = np.array(x)

In [5]:
y = np.array([1,2,3,4,5])
print(y.ndim) #dimension count
print(y.shape) #shape of array
print(y.size) #element count

1
(5,)
5


In [6]:
z = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(z.ndim)
print(z.shape) #shape of array
print(z.size)
print(z)

2
(3, 3)
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
a = np.arange(10,100,.1)
print(a.size)


900


In [8]:
az = a.reshape((30,30))
print(az.shape)

(30, 30)


In [11]:
a3 = a.reshape((30,10,2))
print(a3)

ValueError: cannot reshape array of size 16 into shape (30,10,2)

In [ ]:
b = np.linspace(1,10,100)
print(b)

In [ ]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)
print(a+b)
print(a.max())
print(a.mean())
print(a.min())
print(a.std())
print(a.sum())
print(a.max(axis=0))
print(a.max(axis=1))
print(a.min(axis=0))
print(a.min(axis=1))

In [ ]:
t = np.arange(-np.pi*3, np.pi, .05)
x = np.sin(t)
y = np.cos(t)
print(x)
print(y)
print(np.pi)


In [ ]:
import matplotlib.pyplot as plt
plt.plot(t,x,'r--o')
plt.plot(t,y,'g:x')
plt.title("visualization")
plt.show()

In [10]:


ab = ([1,2,3,4], [6,4,2,2], [2,3,4,3],[1,2,4,1])
a = np.array(ab)
print(a[1:,0:3])


[[6 4 2]
 [2 3 4]
 [1 2 4]]
